>>> from books_authors_app.models import*
>>> Books.objects.create(title="C Sharp",desc="Programming Languge")
<Books: Books object (1)>
>>> Books.objects.create(title="Java",desc="Programming Languge")
<Books: Books object (2)>
>>> Books.objects.create(title="Python",desc="Programming Languge")
<Books: Books object (3)>
>>> Books.objects.create(title="PHP",desc="Programming Languge")
<Books: Books object (4)>
>>> Books.objects.create(title="Ruby",desc="Programming Languge")
<Books: Books object (5)>
>>> Authors.objects.create(first_name="Jane",last_name="Austen")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Authors' is not defined
>>> Authours.objects.create(first_name="Jane",last_name="Austen")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 420, in create
    obj = self.model(**kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/base.py", line 501, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: Authours() got an unexpected keyword argument 'last_name'
>>> Authours.objects.create(first_name="Jane",Last_name="Austen")
<Authours: Authours object (1)>
>>> Authours.objects.create(first_name="Emily",Last_name="Dickinson")
<Authours: Authours object (2)>
>>> Authours.objects.create(first_name="Fyodor",Last_name="Dostoevsky")
<Authours: Authours object (3)>
>>> Authours.objects.create(first_name="William",Last_name="Shakespaeare")
<Authours: Authours object (4)>
>>> Authours.objects.create(first_name="Lau",Last_name="Tzu")
<Authours: Authours object (5)>
>>> exit()
(djangoPy3Env) macbookpro@MacBookPros-MacBook-Pro books_authors_shell % python manage.py makemigrations
You are trying to add a non-nullable field 'notes' to authours without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> ""
Migrations for 'books_authors_app':
  books_authors_app/migrations/0002_authours_notes.py
    - Add field notes to authours
(djangoPy3Env) macbookpro@MacBookPros-MacBook-Pro books_authors_shell % python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, books_authors_app, contenttypes, sessions
Running migrations:
  Applying books_authors_app.0002_authours_notes... OK
(djangoPy3Env) macbookpro@MacBookPros-MacBook-Pro books_authors_shell % python manage.py shell         
Python 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> this_book = Books.objects.get(id=1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Books' is not defined
>>> from books_authors_app import*
>>> this_book = Books.objects.get(id=1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Books' is not defined
>>> from books_authors_app.models import*
>>> this_book = Books.objects.get(id=1)
>>> this_book.title="C#"
>>> this_author = Authours.objects.get(id=4)
>>> this_author.first_name = "Bill"
>>> this_author = Authours.objects.get(id=1)
>>> this_book = Books.objects.get(id=1)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=2)
>>> this_author.books.add(this_book)
>>> this_author = Authours.objects.get(id=2)
>>> this_book = Books.objects.get(id=1)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=2)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=3)
>>> this_author.books.add(this_book)
>>> this_author = Authours.objects.get(id=3)
>>> this_book = Books.objects.get(id=1)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=2)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=3)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=4)
>>> this_author.books.add(this_book)
>>> this_author = Authours.objects.get(id=4)
>>> this_book = Books.objects.get()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 410, in get
    raise self.model.MultipleObjectsReturned(
books_authors_app.models.Books.MultipleObjectsReturned: get() returned more than one Books -- it returned 5!
>>> this_book = Books.objects.get(id=1)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=2)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=3)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=4)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=5)
>>> this_author.books.add(this_book)
>>> this_book = Books.objects.get(id=3)
>>> Authours.objects.get(this_book)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 399, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1315, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1187, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable Books object
>>> Authours.objects.get(id=this_book)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 399, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1315, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Books'
>>> Authours.objects.filter(books=this_book)
<QuerySet [<Authours: Authours object (2)>, <Authours: Authours object (3)>, <Authours: Authours object (4)>]>
>>> this_book = Books.objects.get(id=3)
>>> this_author = Authours.objects.first.filter(books=this_book)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'function' object has no attribute 'filter'
>>> this_author = Authours.objects.filter(books=this_book)
>>> this_author.first()
<Authours: Authours object (2)>
>>> this_author.first().delete()
(4, {'books_authors_app.Authours_books': 3, 'books_authors_app.Authours': 1})
>>> this_author.first()
<Authours: Authours object (3)>
>>> this_book = Books.objects.get(id=2)
>>> this_author = Authours.objects.get(id=5)
>>> this_author.books.add(this_book)
>>> this_author= Authours.get(id=3)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: type object 'Authours' has no attribute 'get'
>>> this_author= Authours.objects.get(id=3)
>>> this_author.books
<django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x7f89594016d0>
>>> this_author.books.value()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'ManyRelatedManager' object has no attribute 'value'
>>> this_author.books.values()
<QuerySet [{'id': 1, 'title': 'C Sharp', 'desc': 'Programming Languge', 'created_at': datetime.datetime(2021, 5, 23, 14, 19, 13, 137307, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 5, 23, 14, 19, 13, 138400, tzinfo=<UTC>)}, {'id': 2, 'title': 'Java', 'desc': 'Programming Languge', 'created_at': datetime.datetime(2021, 5, 23, 14, 19, 31, 925540, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 5, 23, 14, 19, 31, 925592, tzinfo=<UTC>)}, {'id': 3, 'title': 'Python', 'desc': 'Programming Languge', 'created_at': datetime.datetime(2021, 5, 23, 14, 19, 41, 77505, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 5, 23, 14, 19, 41, 77557, tzinfo=<UTC>)}, {'id': 4, 'title': 'PHP', 'desc': 'Programming Languge', 'created_at': datetime.datetime(2021, 5, 23, 14, 19, 50, 317942, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 5, 23, 14, 19, 50, 317992, tzinfo=<UTC>)}]>
>>> this_author.books.name
>>> this_author.books.name.values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'values'
>>> this_author.books.get(name)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'name' is not defined
>>> this_author.books.values()
<QuerySet [{'id': 1, 'title': 'C Sharp', 'desc': 'Programming Languge', 'created_at': datetime.datetime(2021, 5, 23, 14, 19, 13, 137307, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 5, 23, 14, 19, 13, 138400, tzinfo=<UTC>)}, {'id': 2, 'title': 'Java', 'desc': 'Programming Languge', 'created_at': datetime.datetime(2021, 5, 23, 14, 19, 31, 925540, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 5, 23, 14, 19, 31, 925592, tzinfo=<UTC>)}, {'id': 3, 'title': 'Python', 'desc': 'Programming Languge', 'created_at': datetime.datetime(2021, 5, 23, 14, 19, 41, 77505, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 5, 23, 14, 19, 41, 77557, tzinfo=<UTC>)}, {'id': 4, 'title': 'PHP', 'desc': 'Programming Languge', 'created_at': datetime.datetime(2021, 5, 23, 14, 19, 50, 317942, tzinfo=<UTC>), 'updated_at': datetime.datetime(2021, 5, 23, 14, 19, 50, 317992, tzinfo=<UTC>)}]>
>>> this_author.books.title
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'ManyRelatedManager' object has no attribute 'title'
>>> this_author.books.values(title)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'title' is not defined
>>> this_author.books.values(Books.title)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 798, in values
    clone = self._values(*fields, **expressions)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/query.py", line 793, in _values
    clone.query.set_values(fields)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 2020, in set_values
    self.add_fields(field_names, True)
  File "/Users/macbookpro/Desktop/python_stack/djangoPy3Env/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1768, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
AttributeError: 'DeferredAttribute' object has no attribute 'split'
>>> this_author.title
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Authours' object has no attribute 'title'
>>> this_author.books.all()
<QuerySet [<Books: Books object (1)>, <Books: Books object (2)>, <Books: Books object (3)>, <Books: Books object (4)>]>
>>> this_book  = Books.objects.get(id=5)
>>> this_book.author.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Books' object has no attribute 'author'
>>> this_book.Authour.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Books' object has no attribute 'Authour'
>>> this_book.Authours.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Books' object has no attribute 'Authours'
>>> this_book.Books.all()
<QuerySet [<Authours: Authours object (4)>]>
>>> 
